clients/urls.py
from django.contrib import admin
from django.urls import path, include

from clients.views import ClientsListView, HomeView, ClientsDetailView, ClientsDeleteView, ClientsCreateView, \
    ClientsUpdateView

app_name = 'clients'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('clients/list', ClientsListView.as_view(), name='clients_list'),
    path('clients/detail/<int:pk>', ClientsDetailView.as_view(), name='clients_detail'),
    path('clients/delete/<int:pk>', ClientsDeleteView.as_view(), name='clients_delete'),
    path('clients/create', ClientsCreateView.as_view(), name='clients_create'),
    path('clients/update/<int:pk>', ClientsUpdateView.as_view(), name='clients_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls', namespace='clients')),
    # path('', include('mailings.urls', namespace='mailings')),
]

mailings/urls.py
# app_name = 'mailings'

clients/models.py
from django.db import models

# Create your models here.


class Clients(models.Model):
    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Введите свою почту')
    full_name = models.CharField(max_length=150, verbose_name='Ф.И.О.', help_text='Введите свое фио')
    comment = models.TextField(verbose_name='Комментарий', help_text='Введите комментарий', blank=True)

    def __str__(self):
        return f'{self.email} {self.full_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['email', 'full_name']

mailings/models.py
from django.db import models


class Message(models.Model):
    topic = models.CharField(max_length=150, verbose_name='Тема письма', help_text='Введите тему письма')
    body = models.TextField(verbose_name='Тело письма', help_text='Введите тело письма')

    def __str__(self):
        return f'{self.topic} {self.body}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['topic']

clients/forms.py
from django.forms import ModelForm, forms

from clients.models import Clients


class ClientsForm(ModelForm):
    class Meta:
        model = Clients
        fields = "__all__"


    def __init__(self, *args, **kwargs):
        super(ClientsForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Введите почту"
        })

        self.fields['full_name'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Введите ФИО"
        })

        self.fields['comment'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Введите коментарий"
        })

clients/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from clients.forms import ClientsForm
from clients.models import Clients


class ClientsListView(ListView):
    model = Clients
    template_name = 'clients/clients_list.html'


class HomeView(TemplateView):
    template_name = "clients/home.html"


class ClientsDetailView(DetailView):
    model = Clients


class ClientsDeleteView(DeleteView):
    model = Clients
    success_url = reverse_lazy('clients:clients_list')


class ClientsUpdateView(UpdateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('clients:clients_list')


class ClientsCreateView(CreateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('clients:clients_list')

mailings/views.py
from django.shortcuts import render

# Create your views here.

clients/templates/clients/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SkyMail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .margins {
            margin: 30px;
        }

        .margins__buttons{
            margin-right: 5px;
            margin-bottom: 5px
        }
    </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SkyMail</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>


    {% include 'clients/header.html' %}
    {% block content %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyMail
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
<!--                    <li><a class="text-muted" href="https://sky.pro/#giftpopup">Мы пишем</a></li>-->
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

clients/templates/clients/clients_confirm_delete.html
{% extends 'clients/base.html' %}
{% block title %}Удалить клиента{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h4 class="card-text">Действительно хотите удалить клиента? <br> {{ object.full_name}}</h4>
                    <div class="card-body">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            Удалить
                        </button>
                        <a class="btn btn-success" href="{% url 'clients:clients_list' %}" role="button">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/clients_detail.html
{% extends 'clients/base.html' %}
{% block title %}Страница клиентов{% endblock %}
{% block content %}
<body>
    <h1>Информация о клиенте</h1>
    <p>Полное имя: {{ object.full_name }}</p>
    <p>Почта: {{ object.email }}</p>
    <p>Комментарий: {{ object.comment }}</p>
    <a class="btn btn-primary" href="{% url 'clients:clients_list' %}" role="button">Назад</a>
</body>
{% endblock %}

clients/templates/clients/clients_form.html
{% extends 'clients/base.html' %}
{% block title %}Создать клиента{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/clients_list.html
{% extends 'clients/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <a class="btn btn-primary margins" href="{% url 'clients:clients_create' %}" role="button">Создать</a>
        {% for clients in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ clients.full_name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ clients.email }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ clients.comment|truncatechars:100 }}</li>
                            </ul>
                            <a class="btn btn-info margins__buttons" href="{% url 'clients:clients_detail' clients.pk %}" role="button">Просмотреть</a>
                            <a class="btn btn-danger margins__buttons" href="{% url 'clients:clients_delete' clients.pk %}" role="button">Удалить</a>
                            <a class="btn btn-warning" href="{% url 'clients:clients_update' clients.pk %}" role="button">Редактировать</a>
                        </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

clients/templates/clients/header.html
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyMail</h1>
    <p class="lead">Добро пожаловать в приложение для рассылок SkyMail</p>
</div>

clients/templates/clients/home.html
{% extends 'clients/base.html' %}

{% block content %}
    <div class="row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

clients/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SkyMail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SkyMail</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyMail</h1>
    <p class="lead">Добро пожаловать в приложение для рассылок SkyMail</p>

        <div class="row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
</div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyMail
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
<!--                    <li><a class="text-muted" href="https://sky.pro/#giftpopup">Мы пишем</a></li>-->
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>